# Generated by Django 5.2.5 on 2025-08-27 18:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название задачи",
                        max_length=255,
                        verbose_name="Название задачи",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Укажите описание задачи",
                        null=True,
                        verbose_name="Описание задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Создано"),
                            ("IN_PROGRESS", "В работе"),
                            ("COMPLETED", "Завершено"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
